// This file is generated by Slice Machine. Update with care!

import Hero from 'slices/Hero';
import Image from 'slices/Image';
import ImageCards from 'slices/ImageCards';
import Quote from 'slices/Quote';
import Text from 'slices/Text';
import TextWithImage from 'slices/TextWithImage';

export {
  Hero,
  Image,
  ImageCards,
  Quote,
  Text,
  TextWithImage,
};

export const components = {
  hero: Hero,
  image: Image,
  image_cards: ImageCards,
  quote: Quote,
  text: Text,
  text_with_image: TextWithImage,
};
